name: Python Server
on:
  push:
    branches:
      - "master"

jobs:
  test_build:
    runs-on: ubuntu-20.04
    steps:
      - name : Checkout
        uses : actions/checkout@v2

      - name: Cache registry
        uses: actions/cache@v2
        with: 
          path: ~/ .cache/pip
          key : ${{ runner.os }}-multiarchitecture
          restore-keys: |
              ${{ runner.os }}-multiarchitecture-

      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: Buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub Login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id  : docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: anindit123456/apple_clone:v1.2

